### ISSUE TITLE
Expiry without eviction

### ISSUE THREAD

**Issue by CheshireSwift** [SamSaffron/lru_redux#12]
Hi, I was just wondering if there were plans to add an equivalent to the soft_ttl functionality from lrucache, or forced expiry on a timer?

My app hits another server for results which change semi-frequently. I'm caching the results for 30 seconds, but I frequently don't fill the cache to the point things get evicted so they just sit there forever. I'm aware I could have a thread call `.expire!` every so often, but ideally I'd like to make entries expire when they've been there for a certain amount of time (i.e. force retrieval without them being evicted).

**Comment by SamSaffron** [comment]
We already have an awesome, super fast TTL cache that @Seberius added, does that work for you? 

https://github.com/SamSaffron/lru_redux/blob/master/lib/lru_redux/ttl/cache.rb

**Comment by CheshireSwift** [comment]
Odd. I tried that and the observed behaviour appeared to be that it never dropped the expired entries (unless I filled the cache). I'll give it another look, thanks.

**Comment by Seberius** [comment]
I see this issue is closed, but I thought I would clarify how the TTL eviction behaves here compared to lrucache.  You should expect similar behavior as lrucache's TTL when using the #fetch method.  LRURedux does not have an equivalent to soft_ttl, as there is only one TTL eviction time.

- TTL time is set at the cache level and can not be set for individual entries.  This is different from lrucache which allows you to override an entry's TTL at insertion.
- TTL eviction occurs at every access, along with the #expire method.  All methods excluding #count and #max_size= will trigger eviction.  This is the same as lrucache.
- All expired entries are evicted at eviction.  This is different from lrucache which only evicts entries that are accessed (and expired).

The expired entries will remain in the cache until the cache accessed again or #expire is called.  As long as the cache in question is regularly accessed (relative to your TTL) the expired entries will be removed and use of #expire is likely redundant.

The behavior you observed maybe the result of adding the entries to cache and then using #count to check for expiration.  If you were accessing the entries or using #to_a to check for expiration and they were still present that would be a bug.  Please let us in that case so we can track it down and apply a fix.

Thanks!
